import Foundation
import TarabdaarCore

// Build-time parameter-documentation generator (2026-07-24).
//
// Renders docs/parameters.md from the LIVE parameter definitions:
//   * `ParamRegistry`  — every parameter of the String instrument
//   * `CompositeParam` — the shipped composite defaults
// Because this executable compiles against the same types the app uses,
// the documentation cannot drift from the parameter set: add, remove, or
// relabel a parameter and the next `tools/build-mac.sh` rewrites the doc.
//
// Usage: paramdoc [output-path]   (no argument = print to stdout)

func num(_ v: Double) -> String {
    if v == v.rounded() && abs(v) < 1e12 {
        return String(Int(v))
    }
    return String(format: "%g", v)
}

// Scope/timing labels and legend texts come from ParamScope/ParamTiming
// in TarabdaarCore — the SAME strings the Parameters tab renders per row,
// so the app and this document cannot tell different stories.

var out = """
<!-- AUTO-GENERATED — DO NOT EDIT.
     Generated by the `paramdoc` executable (Packages/TarabdaarCore/Sources/paramdoc)
     from the live parameter definitions; regenerated on every
     `tools/build-mac.sh` run. To change this document, change the
     definitions: ParamRegistry (ParamRegistry.swift) and CompositeParam
     (CompositeParams.swift). -->

# Tarabdaar Parameters

Tarabdaar has **one parameter list** — every knob of the String instrument,
edited in the Mac's **Parameters** tab, in native units. There is no
separate "performance parameter" or "physics scalar" category: a
parameter is a parameter, and any of them can be bound to a tilt or added
to a composite.

Each parameter carries two audit columns (2026-08-23):


"""

// ---- Scope/timing legends (the SHARED strings the app also renders) ----
out += "**Scope** — who it acts on:\n\n| Scope | Meaning |\n|---|---|\n"
for s in [ParamScope.global, .perNote] {
    out += "| `\(s.label)` | \(s.explanation) |\n"
}
out += """

The line follows per-note CONTROL STATE, not physics plumbing: friction
and string-construction values are `global` even though every string
evaluates them — they carry no per-note state and cannot differ between
simultaneous notes.

**Timing** — when a change is heard:

| Timing | Meaning |
|---|---|

"""
for t in [ParamTiming.live, .inPlace, .rebuild, .hybrid] {
    out += "| `\(t.label)` | \(t.explanation) |\n"
}
out += """

A few `live`-routed keys carry an explicit `rebuild` timing because
their setter schedules a slow re-mount (the tanpura register/scale-shape
family — seconds of CPU, debounced). The one shipped hybrid (vibrato
depth) used to appear twice under separate names (`bow_vibrato`); it is
one knob now.

**Composite parameters** are named 0–1 macros built from these
parameters: each member sweeps its own low→high range as the composite
rises. Tilts can bind to a composite or to a single parameter directly.

The iPad streams only its raw tilt values; the Mac evaluates every
binding below.


"""

// ---- Composite parameters ----------------------------------------------
out += "## Composite parameters\n\n"
out += "A composite always ranges 0–1 and is built from parameters: each\n"
out += "member lists the value it holds at composite = 0 and at composite = 1\n"
out += "(a reversed pair means the sweep is inverted). There are 8 slots;\n"
out += "below are the shipped defaults (all editable in-app).\n\n"
for c in CompositeParam.defaults() {
    out += "### \(c.name)\n\n"
    out += "| Parameter | At 0 | At 1 | Notes |\n|---|---|---|---|\n"
    for m in c.members {
        let spec = ParamRegistry.spec(m.key)
        let label = spec?.label ?? m.key
        out += "| \(label) (`\(m.key)`) | \(num(m.lo)) | \(num(m.hi)) | \(spec?.help ?? "") |\n"
    }
    out += "\n"
}

// ---- The parameter list -------------------------------------------------
out += "## Parameters\n\n"
out += "Ranges are the editor's slider bounds; defaults are the shipped\n"
out += "artifact values (a value loaded outside its range widens the\n"
out += "slider rather than being clamped).\n\n"
for (group, params) in ParamRegistry.groups {
    out += "### \(group)\n\n"
    out += "| Key | Name | Range | Default | Scope | Timing | Description |\n"
    out += "|---|---|---|---|---|---|---|\n"
    for p in params {
        var def = num(p.def)
        if p.apply == .hybrid, let rest = p.restFraction {
            def = "\(num(p.def)) built · rests at \(num(rest))× the built value"
        }
        out += "| `\(p.key)` | \(p.label) | \(num(p.lo)) … \(num(p.hi)) | \(def) | \(p.scope.label) | \(p.timing.label) | \(p.help) |\n"
    }
    out += "\n"
}

// ---- write -------------------------------------------------------------
if CommandLine.arguments.count > 1 {
    let path = CommandLine.arguments[1]
    do {
        try out.write(toFile: path, atomically: true, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(
            Data("paramdoc: write failed: \(error)\n".utf8))
        exit(1)
    }
} else {
    print(out)
}
