import Foundation
import SarangiKit
import TarabdaarCore

// Build-time parameter-documentation generator .
//
// Renders docs/parameters.md from the LIVE parameter definitions:
//   * `ParamRegistry`  — every instrument, control and FX parameter
//   * `CompositeParam` — the shipped composite defaults
// Because this executable compiles against the same types the app uses,
// the documentation cannot drift from the parameter set: add, remove, or
// relabel a parameter and the next `tools/build-mac.sh` rewrites the doc.
//
// Usage: paramdoc [output-path]   (no argument = print to stdout)

/// Keep structured help inside one Markdown table cell.
func helpCell(_ text: String) -> String {
    text.replacingOccurrences(of: "|", with: "&#124;")
        .replacingOccurrences(of: "\nLow: ", with: "<br>**Low:** ")
        .replacingOccurrences(of: "\nHigh: ", with: "<br>**High:** ")
        .replacingOccurrences(of: "\n", with: "<br>")
}

func num(_ v: Double) -> String {
    if v == v.rounded() && abs(v) < 1e12 {
        return String(Int(v))
    }
    return String(format: "%g", v)
}

// THE SHIPPED DEFAULT of a build scalar is the ARTIFACT's value, not the
// registry's authored one — the fit moves values wherever the physics
// wants them, and `AppController.paramDefault` resolves
// `artifactValue(key) ?? spec.def` for every `.rebuild`/`.hybrid` key.
// This document resolves the same way, so the Default column matches
// what the Parameters tab shows and what the engine actually runs.
let artifact = Presets.bowedStringParams()?.num ?? [:]

/// The value the parameter RESTS at in the shipped instrument, plus the
/// authored registry default when the artifact overrides it.
func shippedDefault(_ p: ParamSpec) -> (value: Double, authored: Double?) {
    guard p.apply != .live, let a = artifact[p.key] else { return (p.def, nil) }
    return (a, a == p.def ? nil : p.def)
}

// Scope/timing labels and legend texts come from ParamScope/ParamTiming
// in TarabdaarCore — the SAME strings the Parameters tab renders per row,
// so the app and this document cannot tell different stories.

var out = """
<!-- AUTO-GENERATED — DO NOT EDIT.
     Generated by the `paramdoc` executable (Packages/TarabdaarCore/Sources/paramdoc)
     from the live parameter definitions; regenerated on every
     `tools/build-mac.sh` run. To change this document, change the
     definitions: ParamRegistry (ParamRegistry.swift) and CompositeParam
     (CompositeParams.swift). -->

# Tarabdaar Parameters

Tarabdaar has **one parameter list** for the String voice, both taraf banks,
Tanpura, Sitar, performance controls and FX. The Mac's **Parameters** tab
edits them in native units. Groups identify the affected voice or stage,
then the musical function. Each description explains the effect and the
meaning of **Low** and **High** values, including zero, neutral points,
switch choices and dependencies where relevant. There is no
separate "performance parameter" or "physics scalar" category: a
parameter is a parameter, and any of them can be bound to a tilt or added
to a composite.

Each parameter carries two audit columns:


"""

// ---- Scope/timing legends (the SHARED strings the app also renders) ----
out += "**Scope** — who it acts on:\n\n| Scope | Meaning |\n|---|---|\n"
for s in [ParamScope.global, .perNote] {
    out += "| `\(s.label)` | \(s.explanation) |\n"
}
out += """

The line follows per-note CONTROL STATE, not physics plumbing: friction
and string-construction values are `global` even though every string
evaluates them — they carry no per-note state and cannot differ between
simultaneous notes.

**Timing** — when a change is heard:

| Timing | Meaning |
|---|---|

"""
for t in [ParamTiming.live, .onset, .inPlace, .rebuild, .hybrid] {
    out += "| `\(t.label)` | \(t.explanation) |\n"
}
out += """

A few `live`-routed keys carry an explicit `rebuild` timing because
their setter schedules a slow re-mount (the tanpura register/scale-shape
family — seconds of CPU, debounced).

**Composite parameters** are named 0–1 macros built from these
parameters: each member sweeps its own low→high range as the composite
rises. Tilts can bind to a composite or to a single parameter directly.

The iPad streams only its raw tilt values; the Mac evaluates every
binding below.


"""

// ---- Composite parameters ----------------------------------------------
out += "## Composite parameters\n\n"
out += "A composite always ranges 0–1 and is built from parameters: each\n"
out += "member lists the value it holds at composite = 0 and at composite = 1\n"
out += "(a reversed pair means the sweep is inverted). There are 8 slots;\n"
out += "below are the shipped defaults (all editable in-app).\n\n"
for c in CompositeParam.defaults() {
    out += "### \(c.name)\n\n"
    out += "| Parameter | At 0 | At 1 | Notes |\n|---|---|---|---|\n"
    for m in c.members {
        let spec = ParamRegistry.spec(m.key)
        let label = spec?.qualifiedLabel ?? m.key
        out += "| \(label) (`\(m.key)`) | \(num(m.lo)) | \(num(m.hi)) | \(helpCell(spec?.help ?? "")) |\n"
    }
    out += "\n"
}

// ---- The parameter list -------------------------------------------------
out += "## Parameters\n\n"
out += "Ranges are the editor's slider bounds; defaults are the values the\n"
out += "shipped instrument RESTS at — the fitted `bowed_string.json` value\n"
out += "wherever the artifact carries the key, with the registry's authored\n"
out += "default in parentheses when the two differ. A value loaded outside\n"
out += "its range widens the slider rather than being clamped.\n\n"
func paramRow(_ p: ParamSpec, key: String? = nil, label: String? = nil,
              help: String? = nil) -> String {
    let shipped = shippedDefault(p)
    var def = num(shipped.value)
    if p.apply == .hybrid, let rest = p.restFraction {
        def = "\(num(shipped.value)) built · rests at \(num(rest))× the built value"
    }
    // the artifact wins; the authored value is shown for reference
    if let a = shipped.authored { def += " (authored \(num(a)))" }
    return "| `\(key ?? p.key)` | \(label ?? p.label) | \(num(p.lo)) … \(num(p.hi)) | \(def) | \(p.scope.label) | \(p.timing.label) | \(helpCell(help ?? p.help)) |\n"
}

let tableHead = "| Key | Name | Range | Default | Scope | Timing | Description |\n"
    + "|---|---|---|---|---|---|---|\n"

for (group, params) in ParamRegistry.groups {
    out += "### \(group)\n\n"
    // A group built from an INSERT DEFINITION instantiated at several
    // points (the FX rack) is documented the way it is defined: the points
    // once, then the insert's knobs once — not N near-identical copies.
    let split = ParamRegistry.insertSections(of: params)
    if !split.flat.isEmpty || split.inserts.isEmpty {
        out += tableHead
        for p in split.flat { out += paramRow(p) }
        out += "\n"
    }
    guard let template = split.inserts.first else { continue }
    out += "The same insert is instantiated at **\(split.inserts.count) points**;\n"
    out += "every key is the point's prefix plus a knob from the table below.\n\n"
    out += "| Insert | Key prefix | What it processes |\n|---|---|---|\n"
    for i in split.inserts {
        out += "| **\(i.point.name)** | `\(i.point.keyPrefix)` | \(i.point.what) |\n"
    }
    out += "\n#### The insert (\(template.params.count) knobs × "
    out += "\(split.inserts.count) points)\n\n"
    out += "Keys below are written `<prefix>knob` — e.g. `fx_voice_rev_mix` is\n"
    out += "the reverb mix of the Voice insert. The EQ curve's points are not\n"
    out += "knobs: the FX tab edits them and presets carry them as a section\n"
    out += "of their own (`fxCurves`). Every knob has the same\n"
    out += "range, default, scope and timing at every point — only the\n"
    out += "\"what it processes\" clause of the two toggles differs.\n\n"
    out += tableHead
    for p in template.params {
        let knob = p.insert?.knob ?? p.key
        // the toggles' help embeds the point's own description; in the
        // shared table it points at the table of points instead
        let help = p.help.replacingOccurrences(
            of: template.point.what,
            with: "what this insert point processes (the table above)")
        out += paramRow(p, key: "<prefix>\(knob)",
                        label: p.insert?.knobLabel, help: help)
    }
    out += "\n"
}

// ---- write -------------------------------------------------------------
if CommandLine.arguments.count > 1 {
    let path = CommandLine.arguments[1]
    do {
        try out.write(toFile: path, atomically: true, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(
            Data("paramdoc: write failed: \(error)\n".utf8))
        exit(1)
    }
} else {
    print(out)
}
