import Foundation
import TarabdaarCore

// Build-time parameter-documentation generator (2026-07-24).
//
// Renders docs/parameters.md from the LIVE parameter definitions:
//   * `ParamRegistry`  — every parameter of the String instrument
//   * `CompositeParam` — the shipped composite defaults
// Because this executable compiles against the same types the app uses,
// the documentation cannot drift from the parameter set: add, remove, or
// relabel a parameter and the next `tools/build-mac.sh` rewrites the doc.
//
// Usage: paramdoc [output-path]   (no argument = print to stdout)

func num(_ v: Double) -> String {
    if v == v.rounded() && abs(v) < 1e12 {
        return String(Int(v))
    }
    return String(format: "%g", v)
}

func scopeLabel(_ s: ParamScope) -> String {
    switch s {
    case .global:  return "global"
    case .perNote: return "per-note"
    }
}

/// The honest apply timing: the registry's strategy is a routing hint,
/// and the truth for `.rebuild` keys depends on `inPlaceKeys` — most of
/// them land on the RUNNING kernel with no rebuild at all.
func timingLabel(_ p: ParamSpec) -> String {
    switch p.apply {
    case .live:    return "live"
    case .hybrid:  return "hybrid"
    case .rebuild:
        return ParamRegistry.inPlaceKeys.contains(p.key)
            ? "in-place" : "rebuild"
    }
}

var out = """
<!-- AUTO-GENERATED — DO NOT EDIT.
     Generated by the `paramdoc` executable (Packages/TarabdaarCore/Sources/paramdoc)
     from the live parameter definitions; regenerated on every
     `tools/build-mac.sh` run. To change this document, change the
     definitions: ParamRegistry (ParamRegistry.swift) and CompositeParam
     (CompositeParams.swift). -->

# Tarabdaar Parameters

Tarabdaar has **one parameter list** — every knob of the String instrument,
edited in the Mac's **Parameters** tab, in native units. There is no
separate "performance parameter" or "physics scalar" category: a
parameter is a parameter, and any of them can be bound to a tilt or added
to a composite.

Each parameter carries two audit columns (2026-08-23):

**Scope** — who it acts on:

| Scope | Meaning |
|---|---|
| `global` | ONE shared mechanism — the bridge/body, the taraf bank, the room/FX/output chain, the shared string physics, or a control axis every note rides together. Changing it moves the whole instrument at once. |
| `per-note` | Runs SEPARATELY for each note: every sounding note carries its own state for it (onset clock, settle/linger envelope, vibrato phase, drift walk, strike-blend window), so simultaneous notes are affected independently. The attack family is CAPTURED at the articulation edge — an edit changes subsequent onsets, never a sounding note. |

The line follows per-note CONTROL STATE, not physics plumbing: friction
and string-construction values are `global` even though every string
evaluates them — they carry no per-note state and cannot differ between
simultaneous notes.

**Timing** — when a change is heard:

| Timing | Meaning |
|---|---|
| `live` | A dedicated runtime setter — instant everywhere, including through tilt/strike bindings and composites. The right kind for continuous real-time control. |
| `in-place` | A build scalar whose change lands on the RUNNING kernel (no rebuild, no lost ring) — but it persists as an override and flushes through a ~0.2 s debounce, in the Parameters tab and through bindings alike. Fine for set-and-listen editing; for continuous binding prefer a `live` parameter. |
| `rebuild` | Needs a fresh engine: ~0.2 s debounce, then an off-main rebuild adopted through a crossfade. |
| `hybrid` | Instant at or below the built headroom (a live 0–1 kernel scaler); pushing above the built value rebuilds. The two hybrids (jawari buzz, vibrato depth) used to appear twice under separate names (`bow_jaw_gain`, `bow_vibrato`) — they are one knob now. |

**Composite parameters** are named 0–1 macros built from these
parameters: each member sweeps its own low→high range as the composite
rises. Tilts can bind to a composite or to a single parameter directly.

The iPad streams only its raw tilt values; the Mac evaluates every
binding below.


"""

// ---- Composite parameters ----------------------------------------------
out += "## Composite parameters\n\n"
out += "A composite always ranges 0–1 and is built from parameters: each\n"
out += "member lists the value it holds at composite = 0 and at composite = 1\n"
out += "(a reversed pair means the sweep is inverted). There are 8 slots;\n"
out += "below are the shipped defaults (all editable in-app).\n\n"
for c in CompositeParam.defaults() {
    out += "### \(c.name)\n\n"
    out += "| Parameter | At 0 | At 1 | Notes |\n|---|---|---|---|\n"
    for m in c.members {
        let spec = ParamRegistry.spec(m.key)
        let label = spec?.label ?? m.key
        out += "| \(label) (`\(m.key)`) | \(num(m.lo)) | \(num(m.hi)) | \(spec?.help ?? "") |\n"
    }
    out += "\n"
}

// ---- The parameter list -------------------------------------------------
out += "## Parameters\n\n"
out += "Ranges are the editor's slider bounds; defaults are the shipped\n"
out += "artifact values (a value loaded outside its range widens the\n"
out += "slider rather than being clamped).\n\n"
for (group, params) in ParamRegistry.groups {
    out += "### \(group)\n\n"
    out += "| Key | Name | Range | Default | Scope | Timing | Description |\n"
    out += "|---|---|---|---|---|---|---|\n"
    for p in params {
        var def = num(p.def)
        if p.apply == .hybrid, let rest = p.restFraction {
            def = "\(num(p.def)) built · rests at \(num(rest))× the built value"
        }
        out += "| `\(p.key)` | \(p.label) | \(num(p.lo)) … \(num(p.hi)) | \(def) | \(scopeLabel(p.scope)) | \(timingLabel(p)) | \(p.help) |\n"
    }
    out += "\n"
}

// ---- write -------------------------------------------------------------
if CommandLine.arguments.count > 1 {
    let path = CommandLine.arguments[1]
    do {
        try out.write(toFile: path, atomically: true, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(
            Data("paramdoc: write failed: \(error)\n".utf8))
        exit(1)
    }
} else {
    print(out)
}
