import Foundation
import StarpadCore

// Build-time parameter-documentation generator (2026-07-24).
//
// Renders docs/parameters.md from the LIVE parameter definitions:
//   * `ParamRegistry`  — every parameter of the String instrument
//   * `CompositeParam` — the shipped composite defaults
// Because this executable compiles against the same types the app uses,
// the documentation cannot drift from the parameter set: add, remove, or
// relabel a parameter and the next `tools/build-mac.sh` rewrites the doc.
//
// Usage: paramdoc [output-path]   (no argument = print to stdout)

func num(_ v: Double) -> String {
    if v == v.rounded() && abs(v) < 1e12 {
        return String(Int(v))
    }
    return String(format: "%g", v)
}

func applyLabel(_ a: ParamApply) -> String {
    switch a {
    case .live:    return "live"
    case .rebuild: return "rebuild"
    case .hybrid:  return "hybrid"
    }
}

var out = """
<!-- AUTO-GENERATED — DO NOT EDIT.
     Generated by the `paramdoc` executable (Packages/StarpadCore/Sources/paramdoc)
     from the live parameter definitions; regenerated on every
     `tools/build-mac.sh` run. To change this document, change the
     definitions: ParamRegistry (ParamRegistry.swift) and CompositeParam
     (CompositeParams.swift). -->

# Starpad Parameters

Starpad has **one parameter list** — every knob of the String instrument,
edited in the Mac's **Parameters** tab, in native units. There is no
separate "performance parameter" or "physics scalar" category: a
parameter is a parameter, and any of them can be bound to a tilt or added
to a composite.

Each parameter has an **apply strategy**:

| Strategy | Meaning |
|---|---|
| `live` | A runtime setter on the engine — takes effect instantly. |
| `rebuild` | A `bowed_string.json` build scalar — applied as a persisted override with a debounced off-main engine rebuild. |
| `hybrid` | A build scalar that also has a live 0–1 scaler in the kernel. At or below the built value it applies instantly; pushing above it rebuilds. |

The two `hybrid` parameters (jawari buzz, vibrato depth) used to appear
**twice** — once as the build scalar and once as the live scaler under a
different name (`bow_jaw_gain`, `bow_vibrato`). They are one knob now.

**Composite parameters** are named 0–1 macros built from these
parameters: each member sweeps its own low→high range as the composite
rises. Tilts can bind to a composite or to a single parameter directly.

The iPad streams only its raw tilt values; the Mac evaluates every
binding below.


"""

// ---- Composite parameters ----------------------------------------------
out += "## Composite parameters\n\n"
out += "A composite always ranges 0–1 and is built from parameters: each\n"
out += "member lists the value it holds at composite = 0 and at composite = 1\n"
out += "(a reversed pair means the sweep is inverted). There are 8 slots;\n"
out += "below are the shipped defaults (all editable in-app).\n\n"
for c in CompositeParam.defaults() {
    out += "### \(c.name)\n\n"
    out += "| Parameter | At 0 | At 1 | Notes |\n|---|---|---|---|\n"
    for m in c.members {
        let spec = ParamRegistry.spec(m.key)
        let label = spec?.label ?? m.key
        out += "| \(label) (`\(m.key)`) | \(num(m.lo)) | \(num(m.hi)) | \(spec?.help ?? "") |\n"
    }
    out += "\n"
}

// ---- The parameter list -------------------------------------------------
out += "## Parameters\n\n"
out += "Ranges are the editor's slider bounds; defaults are the shipped\n"
out += "artifact values (a value loaded outside its range widens the\n"
out += "slider rather than being clamped).\n\n"
for (group, params) in ParamRegistry.groups {
    out += "### \(group)\n\n"
    out += "| Key | Name | Range | Default | Apply | Description |\n"
    out += "|---|---|---|---|---|---|\n"
    for p in params {
        var def = num(p.def)
        if p.apply == .hybrid, let rest = p.restFraction {
            def = "\(num(p.def)) built · rests at \(num(rest))× the built value"
        }
        out += "| `\(p.key)` | \(p.label) | \(num(p.lo)) … \(num(p.hi)) | \(def) | \(applyLabel(p.apply)) | \(p.help) |\n"
    }
    out += "\n"
}

// ---- write -------------------------------------------------------------
if CommandLine.arguments.count > 1 {
    let path = CommandLine.arguments[1]
    do {
        try out.write(toFile: path, atomically: true, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(
            Data("paramdoc: write failed: \(error)\n".utf8))
        exit(1)
    }
} else {
    print(out)
}
