import Foundation

/// Captured SWAM Violin AU `fullStateForDocument` (binary plist, base64).
///
/// This carries SWAM's OPAQUE encoded state — notably the per-control MIDI CC
/// assignments (Expression / Vibrato Depth / Bow Pressure / Bow/Pizz Position),
/// which SWAM does NOT expose as AU parameters and so can't be set via the
/// `hostedAUParams` dictionary. The mapping has to be configured once in SWAM's
/// own MIDI-mapping UI; this file is then regenerated by
/// `AppController.captureSwamState()` (the "Capture SWAM State" button) to bake
/// that configured state into the app.
///
/// Workflow:
///   1. Run StarpadMac, open the SWAM view, assign the desired CCs.
///   2. Click "Capture SWAM State" — this file is overwritten with the new blob.
///   3. Rebuild. `.swamViola` restores it to every SWAM slot on launch (applied
///      before the `hostedAUParams`, so the coded parameter values still win).
///
/// An empty string = nothing captured yet → `violin` is nil → restore is a
/// no-op. DO NOT hand-edit the base64; regenerate it via the capture button.
enum SwamDefaultState {
    /// base64 of the binary-plist `fullStateForDocument`. Empty until captured.
    static let violinBase64 = ""

    /// Decoded state ready for `AudioEngine.setHostedAUFullState`, or nil.
    static var violin: Data? {
        violinBase64.isEmpty ? nil : Data(base64Encoded: violinBase64)
    }
}
