import XCTest
@testable import SarangiKit

/// Sample-parity test for the Swift ViolinSynth port against the Python
/// reference (src/violin/model.py). Goldens are generated by
/// app/tools/gen_violin_golden.py from a SYNTHETIC mini model in
/// DETERMINISTIC mode (no jitter/noise), so the harmonic path must match
/// Python at float64 precision up to libm sin() differences.
final class ViolinParityTests: XCTestCase {
    func loadGolden() throws -> (model: ViolinModel, golden: [String: Any]) {
        let dir = Bundle.module.url(forResource: "Goldens", withExtension: nil)!
        let model = try ViolinModel(url: dir.appendingPathComponent("violin_mini_model.json"))
        let data = try Data(contentsOf: dir.appendingPathComponent("violin_golden.json"))
        let golden = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        return (model, golden)
    }

    func testDeterministicParity() throws {
        let (model, golden) = try loadGolden()
        let block = golden["block"] as! Int
        let frames = golden["frames"] as! [[String: Any]]
        let refRMS = (golden["block_rms"] as! [NSNumber]).map { $0.doubleValue }
        let sampleBlocks = golden["sample_blocks"] as! [String: [NSNumber]]

        let synth = ViolinSynth(model: model, block: block, deterministic: true)
        if let sy = golden["symp"] as? [String: Any] {
            let parts = (sy["partials"] as! [[NSNumber]]).map {
                (freq: $0[0].doubleValue, tau: $0[1].doubleValue)
            }
            synth.symp = SympatheticWeb(
                partials: parts, dt: Double(block) / model.sr,
                k: (sy["k"] as! NSNumber).doubleValue,
                winHz: (sy["win_hz"] as! NSNumber).doubleValue)
        }
        var out = [Double](repeating: 0, count: block)
        var maxRMSErr = 0.0
        var maxSampErr = 0.0
        for (i, f) in frames.enumerated() {
            let c = ViolinControlFrame(
                f0: (f["f0"] as! NSNumber).doubleValue,
                expr: (f["expr"] as! NSNumber).doubleValue,
                press: (f["press"] as! NSNumber).doubleValue,
                pos: (f["pos"] as! NSNumber).doubleValue,
                gate: (f["gate"] as! NSNumber).boolValue,
                legato: (f["legato"] as! NSNumber).boolValue,
                tiltDb: (f["tilt"] as? NSNumber)?.doubleValue ?? 0)
            synth.process(c, into: &out)
            var sum = 0.0
            for v in out { sum += v * v }
            let rms = (sum / Double(block)).squareRoot()
            maxRMSErr = max(maxRMSErr, abs(rms - refRMS[i]))
            if let ref = sampleBlocks[String(i)] {
                for (j, r) in ref.enumerated() {
                    maxSampErr = max(maxSampErr, abs(out[j] - r.doubleValue))
                }
            }
        }
        print(String(format: "violin parity: max block-RMS err %.3e, max sample err %.3e",
                     maxRMSErr, maxSampErr))
        XCTAssertLessThan(maxRMSErr, 1e-9, "block RMS diverges from Python reference")
        XCTAssertLessThan(maxSampErr, 1e-8, "samples diverge from Python reference")
    }

    /// Real-model speed (64 harmonics + 24 noise bands): reads the fitted
    /// params/violin_model.json from the repo if present (skips otherwise).
    /// This is the number that matters for live playing.
    func testRealModelSpeed() throws {
        #if DEBUG
        throw XCTSkip("speed is meaningful in release builds only (swift test -c release)")
        #endif
        let path = FileManager.default.currentDirectoryPath + "/../params/violin_model.json"
        try XCTSkipUnless(FileManager.default.fileExists(atPath: path),
                          "fitted model not present")
        let model = try ViolinModel(url: URL(fileURLWithPath: path))
        let synth = ViolinSynth(model: model, block: 256)
        var out = [Double](repeating: 0, count: 256)
        let c = ViolinControlFrame(f0: 220, expr: 0.8, press: 0.6, pos: 0.5, gate: true)
        let blocks = 1000
        let t0 = Date()
        for _ in 0..<blocks { synth.process(c, into: &out) }
        let wall = Date().timeIntervalSince(t0)
        let audioSec = Double(blocks * 256) / model.sr
        print(String(format: "violin synth REAL model speed: %.1fx realtime", audioSec / wall))
        XCTAssertGreaterThan(audioSec / wall, 1.5, "real model too slow for realtime")
    }

    /// Rough real-time budget check with the mini model: full-rate rendering
    /// must be far faster than realtime even unoptimized.
    func testRenderSpeed() throws {
        let (model, _) = try loadGolden()
        let synth = ViolinSynth(model: model, block: 256)
        var out = [Double](repeating: 0, count: 256)
        let c = ViolinControlFrame(f0: 220, expr: 0.8, press: 0.6, pos: 0.5, gate: true)
        let blocks = 2000                            // ~10.7 s of audio
        let t0 = Date()
        for _ in 0..<blocks { synth.process(c, into: &out) }
        let wall = Date().timeIntervalSince(t0)
        let audioSec = Double(blocks * 256) / model.sr
        print(String(format: "violin synth speed: %.1fx realtime", audioSec / wall))
        XCTAssertGreaterThan(audioSec / wall, 4.0, "synth too slow for realtime")
    }
}
